In [1]:
#TASK-1 LAB-4

import numpy as np

X = np.arange(2, 33, 2).reshape(4, 4)
print(X)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [2]:
#TASK-2 LAB-4

import numpy as np

X = np.arange(1, 26).reshape(5, 5)

Y = X[X % 2 != 0]

print("Original Array:")
print(X)
print("\nArray with Odd Numbers:")
print(Y)


Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array with Odd Numbers:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [3]:
#TASK-3 LAB-4

import numpy as np

X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [4]:
#TASK-4 LAB-4

from google.colab import drive
drive.mount('/NumPy.ipynb')

import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)

# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

Mounted at /NumPy.ipynb
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[ 1.26396975 -0.29205464 -1.23461279 ... -1.77758203 -0.61258206
  -0.0114063 ]
 [-1.31548634  1.25921619  0.91273047 ... -1.18982207 -0.5793061
  -0.71463319]
 [-0.11059982 -0.92078163 -0.22752544 ...  0.91596025 -1.36961022
  -1.26731591]
 ...
 [-0.77564792 -0.48450811  1.50297243 ...  0.12369987  0.42382554
   1.59164855]
 [ 0.18497711  1.62631604  0.0235528  ... -0.31318739  1.56907328
   1.39917198]
 [ 0.82539379  1.56810058 -1.27276003 ... -1.51301854 -0.77133613
  -1.25562983]]
Average of all values in X_norm: 1.2789769243681803e-17
Average of minimum values in each column of X_norm: -1.733960276080304
Average of maximum values in each column of X_norm: 1.721249842174832
Random permutation of row indices: [753 353  85  50 794 714 377 887 118 112 690 507 423 789 294 124 436 239
  96 991 370  94 723 649 702 469 684  83 825 242 854 201 868 826 301 678
 120 901 332 472 487 388 28